/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendencepromyown;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 *
 * @author SEMH
 */
public class LateAttendance extends javax.swing.JFrame {

    /**
     * Creates new form InOut
     */
    public LateAttendance() {
        initComponents();
        sPinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.util.Date d = new java.util.Date();
        SpinnerDateModel sm = new SpinnerDateModel(d,null,null,Calendar.HOUR_OF_DAY);
        sni = new javax.swing.JSpinner(sm);
        jButton2 = new javax.swing.JButton();
        cbo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jUsername = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JSpinner.DateEditor de = new JSpinner.DateEditor(sni,"hh:mm:ss");
        sni.setEditor(de);
        sni.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        sni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sni.setOpaque(false);
        getContentPane().add(sni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, 42));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 130, 30));

        cbo.setBackground(new java.awt.Color(0, 102, 204));
        cbo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbo.setForeground(new java.awt.Color(255, 255, 255));
        cbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Value", "Morning Half Day", "Evening Half Day", "After 9", "After 10", "After 11" }));
        cbo.setOpaque(false);
        getContentPane().add(cbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jUsername.setOpaque(false);
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 50));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Untitled-1.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 255, 255));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(false);

        jMenu1.setText("File");

        jMenu3.setText("View User Details");
        jMenu1.add(jMenu3);

        jMenu4.setText("View Attendence Table");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        jMenuBar1.setBackground(Color.red);
//        jMenuBar1.setForeground(Color.red);
//        jMenuBar1.setBackground(new java.awt.Color(51, 11, 255));
//       cbo.getEditor().getEditorComponent().setBackground(Color.BLACK);
//        ((JTextField) cbo.getEditor().getEditorComponent()).setOpaque(true);
//         cbo.getEditor().getEditorComponent().setBackground(Color.YELLOW);
//        ((JTextField) cbo.getEditor().getEditorComponent()).setBackground(Color.YELLOW);
         cbo.setBounds(149, 99, 155, 20);
    cbo.setOpaque(false);
    //comboBox.setBackground(new Color(0,0,0,0));
    ((JTextField)cbo.getEditor().getEditorComponent()).setOpaque(false);
    cbo.setUI(new BasicComboBoxUI(){  

        public void paintCurrentValueBackground(Graphics g,Rectangle bounds,boolean hasFocus){}});  
    //frame.getContentPane().add(cbo);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        cbo.setBackground(Color.PINK);
//cbo.setForeground(Color.ORANGE);
//cbo.setFocusable(false);
        //jUsername.setBounds(520, 284, 190, 25);  
    //jUsername.setOpaque(false);  
   // jUsername.setBorder(null);  
    //getContentPane().add(jUsername);  
        
//        sni.setOpaque(false);
//sni.getEditor().setOpaque(false);
//((JSpinner.DefaultEditor)sni.getEditor()).getTextField().setOpaque(false);
        
        //menu bar
        UIManager.put("Menu.background", Color.GREEN);
                UIManager.put("MenuItem.background", Color.MAGENTA);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LateAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LateAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jUsername;
    private javax.swing.JSpinner sni;
    // End of variables declaration//GEN-END:variables

    private void sPinner() {
         Component c = sni.getEditor().getComponent(0);
        c.setForeground(Color.BLUE);
        JComponent editor = sni.getEditor();
        JSpinner.DefaultEditor spinnerEditor = (JSpinner.DefaultEditor)editor;
        spinnerEditor.getTextField().setHorizontalAlignment(JTextField.CENTER);
    }
}
